---
   
- hosts: MyHorizonVMs       # my list of VMs on horizon cloud.This entry is in our inventory file
  remote_user:  ubuntu      # remote user is ubuntu
  become: yes               # run as sudo
  gather_facts: no
  
  tasks:
  - name: Installing Python packages
    apt:
      name: "{{ item }}"
      update_cache: yes      
    with_items:
      - python-dev
      - python-setuptools
      - python-pip
   
  - name: Install various libraries with pip
    pip: 
      name: "{{ item }}"
    with_items:
      - flask
      - numpy
  
  - name: Copy script
    copy: src=assign2_server.py dest=/home/ubuntu/assign2_server.py
  
  - name: Run Assignment2 Server
    shell: python assign2_server.py
    async: 110
    poll: 0


- hosts: MyLocalVMs
  remote_user: ubuntu
  become: yes
  gather_facts: no
  
  tasks:
  - name: Run Assignment2 Client
    raw: "python assign2_client.py"
  
  

...